# Generated by Django 5.0.14 on 2026-05-04 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanfeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_item', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'danfe_itens',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inventario', models.DateField()),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inventarios',
                'ordering': ['-data_inventario'],
            },
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_contada', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_diferenca', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inventario_itens',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('data_movimento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'tipos_movimentacao',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Danfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.PositiveIntegerField(default=1)),
                ('chave_44', models.CharField(max_length=44, unique=True, validators=[django.core.validators.RegexValidator(message='A chave de NF-e deve ter exatamente 44 dígitos numéricos.', regex='^\\d{44}$')])),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='danfes', to='produtos.fornecedor')),
            ],
            options={
                'db_table': 'danfes',
                'ordering': ['-adicionado_em'],
            },
        ),
    ]
