# Generated by Django 5.0.14 on 2026-05-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, help_text='CNPJ / CPF / outro', max_length=20, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tipo_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores', to='produtos.tipofornecedor', verbose_name='Tipo de fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo_lote',
            field=models.CharField(max_length=80, verbose_name='Código do lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produtos.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='controla_validade',
            field=models.BooleanField(default=True, verbose_name='Controlar validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=16, verbose_name='Unidade de medida'),
        ),
        migrations.AlterField(
            model_name='tipofornecedor',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
    ]
